package: link_checker
version: '1.0.0-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/link_checker
# load: late 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"
        yrewrite: ">1"

page:
    title: translate:link_checker_title
    icon: rex-icon fa-link

pages:
    link_checker:
        title: translate:link_checker_title
        icon: rex-icon fa-link
        perm: link_checker[]
        subpages:
            links:
                title: translate:link_checker_links
                icon: rex-icon fa-link
                perm: admin
            source:
                title: translate:link_checker_source
                icon: rex-icon fa-file-text-o
                perm: admin
            docs:
                title: translate:link_checker_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                perm: link_checker[docs]
            settings:
                title: translate:link_checker_settings
                icon: rex-icon fa-gear
                perm: admin
default_config:
    populated: 0
