package: link_checker
version: '0.0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/link_checker
# load: late 

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"

page:
    title: translate:link_checker_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    link_checker:
        title: translate:link_checker_title
        icon: rex-icon fa-calendar
        perm: link_checker[]
        subpages:
            links:
                title: translate:link_checker_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            settings:
                title: translate:link_checker_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:link_checker_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: link_checker[docs]

default_config:
    field: 'Test'
